{% set version = "0.5.4" %}

package:
  name: jupyterlab_launcher
  version: {{ version }}

source:
  fn: jupyterlab_launcher-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_launcher/jupyterlab_launcher-{{ version }}.tar.gz
  sha256: ed1e121be33529bc914400387b3676337e31b9154b92fabe05b954376f3d5990

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - notebook

test:
  imports:
    - jupyterlab_launcher

about:
  home: http://github.com/jupyterlab/jupyterlab_launcher
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A Launcher for JupyterLab based applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
