{% set version = "0.2.8" %}

package:
  name: jupyterlab_launcher
  version: {{ version }}

source:
  fn: jupyterlab_launcher-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_launcher/jupyterlab_launcher-{{ version }}.tar.gz
  sha256: f3ec342f558efd419040d35afd13396e2bb8101cef5bdb600a8c64679218d8a5

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - notebook

test:
  imports:
    - jupyterlab_launcher

about:
  home: http://github.com/jupyterlab/jupyterlab_launcher
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A Launcher for JupyterLab based applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
