# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eBEw1+IwoHVTh4ePGhVI9Y7mSHT95910DrWJxzmFrzB5ptqk84j/HBUpTWe8fbKHLbF98eCuhutrQC7OsocAm/Qsru4Nch2tU6pBCKzNjIYXG5u5/qFC2xzE3jcuc5xEIk8u7oOEiz0vKJpzwJeswAl3OygmfoCKXT2Ka0PSevU6r3UzIe9FCxh/QfNnQN3RjFZGK2uH/luw229CkPNHyteLocdQDomg1M9klhAJTVa0Cxv+6XL5yv6HUwLvKc4258oxkf27N/lTr1kUM5uVISpV5zUPxH51jjiAxQVcX5vY+gHp0wqXy1+ffl0+mCJtGzo02OtmzBnstxkRhckgB+xl58QXLZuV6nuHzAsR3Y56BBvagLXxqbgH3byyAQbcgc1PilaP1En5yoh0c4Qdxzdjz5l9tAWfpIktLc4fh1tFcQkjUCENmnNliSOcCGx5dTMhZInTBcTdjQtfT5bjkT9gTrkihhvzQJvDa1zBHfZnogmzKQdM2U6+6IfhKFVI7DK/lbwtg4YddzZlkUujTo97v/gQT8k7WW2HSJ/Hjs5Ke+pU+RcnZmYi2mV/TMUyBk7KVir4KWyuwIlG21oz4M/92FUPZPXFqjw6zH7d+NcphXRUN82LkkiC9svKYjx9O43BxEevpseBDfaSEMG8ABxra/9WBkiPpTRlNV0sXtQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
