travis:
  secure:
    BINSTAR_TOKEN: eBEw1+IwoHVTh4ePGhVI9Y7mSHT95910DrWJxzmFrzB5ptqk84j/HBUpTWe8fbKHLbF98eCuhutrQC7OsocAm/Qsru4Nch2tU6pBCKzNjIYXG5u5/qFC2xzE3jcuc5xEIk8u7oOEiz0vKJpzwJeswAl3OygmfoCKXT2Ka0PSevU6r3UzIe9FCxh/QfNnQN3RjFZGK2uH/luw229CkPNHyteLocdQDomg1M9klhAJTVa0Cxv+6XL5yv6HUwLvKc4258oxkf27N/lTr1kUM5uVISpV5zUPxH51jjiAxQVcX5vY+gHp0wqXy1+ffl0+mCJtGzo02OtmzBnstxkRhckgB+xl58QXLZuV6nuHzAsR3Y56BBvagLXxqbgH3byyAQbcgc1PilaP1En5yoh0c4Qdxzdjz5l9tAWfpIktLc4fh1tFcQkjUCENmnNliSOcCGx5dTMhZInTBcTdjQtfT5bjkT9gTrkihhvzQJvDa1zBHfZnogmzKQdM2U6+6IfhKFVI7DK/lbwtg4YddzZlkUujTo97v/gQT8k7WW2HSJ/Hjs5Ke+pU+RcnZmYi2mV/TMUyBk7KVir4KWyuwIlG21oz4M/92FUPZPXFqjw6zH7d+NcphXRUN82LkkiC9svKYjx9O43BxEevpseBDfaSEMG8ABxra/9WBkiPpTRlNV0sXtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
