travis:
  secure:
    BINSTAR_TOKEN: RCkLkU73UNelXGXPh2wTszAG7zczK/FOQ8PDSfTmNBJffhGcq879Oqk5r3187k7SxXvEX0ilsY1iNzWd3cBisGfqwxa9TzYM4VSBE0vUd5QL6G+QW2VDOC9rdDiTLDY/ztmkWpKdpD5A1NjJ09oIfYNI9exsILLENblgf7iE9Urs0R0n1kFcqZABwKsMSvzTwA2QMZB0QIjPiFWjArt5aQ8DL0BeSS622nWwQjdbbgDgso63H4pgAa8wIu93S1Mdsf4iyaJtPUE1bzNVMuKBvJjSSfdAPzVQPc1BRTcxsY9ljaXzBqbGpKMDo7h6urI2CWClDW6N6pbHUzOzuHBRBqq0aNRfacv4OP1xxmeH2fnPwE3Bv5WXSypmSNkm4eMjMF43Nq3dml/GdETzsO8vcKpgsGInI82qcnF4TjbWONlJKsQygFcnsfQftBRTLfmFGi4tacMekZzwGJaggsy7riegpJ2M5ARSGADF0WCLkrDlEkqjF7aOfk2JJXMvKsja1Pb2tQumCORPDTHiMZzEnZUEgwsl1ue7XbxtzmC7ROAeMWVG8FRp1xk731mmOQdobYclpBnFRcoJHIPWTP1W9ZdGF/KLVvVtGoXdiwVZj8vygRfV9vVkWP+Jyqe2tZ7k8Kua5bdDcl9S7t0E42kGzJftau68YtqBSm068UhQzVs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
