travis:
  secure:
    BINSTAR_TOKEN: B+/0j5lh96lGLUs1yGumGIy/eqXpxzUekd79JUJAZpI22i5nZ0deLd3roEgOvnS2Bp63dHUMv3z6lBGX0055wmpnApR+PDIlBIkVdOK/E3HcV1S1AvnjgCdt9FRlp/WwQB6MUEvbI4rZ0vjX0oXaCZtpTOt2YBXKxKP7yI2v7P4NwbdcRphGh4oJQbz94dP/QJ7U4eKtu+DmGh+F+kBTdjcCBJvp8V+5Bw5AOu1FcX2cn/+myz11k+UY+R7ILM4GlvVFPiqJ1Cu8dNjreBHZz1NpqCVGDaDe5P0zNcQBV/lIinFG4ePvYEcgPer+05qwPmuQZ2ZS1D5oYpL/qFWrG235uNIp+Bo4+95WP4BAldVSbRW6yiBfT/eZJJ9b0oNBABEST5Ut3RLBQN064/VdR3xAlx9tsCHJpm8dK7CjHa9VbS8KWStDxg5mgrSDM1eeHmzYcI/BOxTeEWLPS/gzzgPf5FetI0JMwyGz/3LO3bWFTLl1+LP6PfvarNw5c9jCXqND5IS14+Cx8V9/Jif8Ts9/S23WaBU2npUyj2MwyMIGfoWgztwWGiOqDap11qhB2kiBYnYxybB1p7pav7O3PWPdrEJ2+VIiC37/vUEofRGTvp6kaiMoCGHCiu3mYTSb3BwuZpakJaefZyYgmrsx9m5fveMwhTA0u+Z0aPhyoIw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
